### ISSUE TITLE
ModuleNotFoundError: No module named 'XCurve.AUROC.losses.PAUCI'

### ISSUE THREAD

**Issue by macaulishxcoo** [statusrank/XCurve#2]
When I execute the file cifar-10_PAUCI.py, the following error appears:  "ModuleNotFoundError: No module named 'XCurve.AUROC.losses.PAUCI'", Is XCurve's current version not matching? my XCurve's current version is:  0.0.6

**Comment by statusrank** [comment]
Thanks for your attention/usage of our package. I am so sorry that the current published version of XCurve on Pypi is not the newest. We are stepping up the development of more XCurves, including AUPRC/AUTKC/AUTKC. Thus, XCurve is expected to conduct a major upgrade next month (we hope so), and then we will release these to Pypi together. For now, you can use XCurve.PAUC by directly downloading our GitHub repo.
